on:
  push:
    branches: [ develop, bugfix/*, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: src/PsPowerBi/bin/Debug/netcoreapp3.1/publish
          name: ${{ matrix.os }}-build
